In [11]:
#question1 
import numpy as np 
a = np.array ([[2,3],[3,3]])
b = a.tolist() 
b

[[2, 3], [3, 3]]

In [28]:
#question2
import numpy as np 
a = np.arange(8).reshape(2,4) 
print(a)
b = np.trace(a) 
b


[[0 1 2 3]
 [4 5 6 7]]


5

In [35]:
#question3
import numpy as np
x = np.array([[1,2],[3,5]]) 
print("this is the array",x)
print("Values bigger than 2 are =", x[x>2])

this is the array [[1 2]
 [3 5]]
Values bigger than 2 are = [3 5]


In [43]:
#question2method2
a =np.array([[2,4],[7,6]]) #2,7
b = a.shape #(2,2)         #7,6 
r=b[0] # 2
sd=0
for i in range(r):
    sd += a[i,i] # 0 + 2 . 2 +6
sd
    


8

In [46]:
#QUESTION4 
a = np.array([[1,2],[3,5]],dtype=np.float64)
b = np.array([[2,3],[4,6]],dtype=np.float64)
c = np.add(a,b)
c



array([[ 3.,  5.],
       [ 7., 11.]])

In [74]:
#question5
a =np.array([[2,4],[7,6]])
a.mean()
print(a)
y=a-a.mean()
y




[[2 4]
 [7 6]]


array([[-2.75, -0.75],
       [ 2.25,  1.25]])